project:
  type: website
  output-dir: "."

website:
  title: "Alexis Kruzicki"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
            
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© Alexis Kruzciki, 2024"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true
    include-after-body: target_blank.html
    
